import { type NextPage } from "next";
import Head from "next/head";
import { useInkathon, } from "@scio-labs/use-inkathon";
import { ConnectButton, GreeterApp } from "@/components/Web3"

const Home: NextPage = () => {

  const { isConnected } = useInkathon()

  return (
    <>
      <Head>
        <title>Rust/Ink Greeter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            use<span className="text-[hsl(280,100%,70%)]">Ink</span> Greeter
          </h1>
          <div className="grid grid-cols-1">
            <ConnectButton />
          </div>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            {
              isConnected &&
              <GreeterApp />
            }
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
